<HTML>
<HEAD>
    <meta charset="utf-8">
    <LINK REL="STYLESHEET" HREF="STYLESHEET.css">
    <title>Добавление новой страны</title>
</HEAD>
<BODY>
<h3><a href="/main">Вернуться на главную</a></h3>
<h3>Добавление новой страны</h3>
<form method="post">
    <p>Введите данные о стране</p>
    <p>Название страны</p>
    <input type="text" name="title">
    <p>Описание страны</p>
    <input type="text" name="description">
    <p>
        <button type="submit">Добавить страну</button>
    </p>
</form>

</BODY>

</HTML>