<HTML>
<HEAD>
    <meta charset="utf-8">
    <LINK REL="STYLESHEET" HREF="STYLESHEET.css">
    <title>Вход в аккаунт</title>
</HEAD>
<BODY>
<h3><a href="/">Вернуться на главную</a></h3>
<h2>Вход в аккаунт</h2>
<form method="post">
    <p>Email</p>
    <input type="text" name="email" required>
    <p>Пароль</p>
    <input type="password" name="password" required>
    <button type="submit">Войти</button>
</form>
</BODY>
</HTML>