<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h2>Please sign in!</h2>
<form name="loggin" method="post" action="/register">
    <p>
        <label>Username</label> <input type="text" name="username" placeholder="Username" required autofocus/>
    </p>
    <p>
        <label>Password</label> <input type="password" name="password" placeholder="Password" required/>
    </p>
    <button type="submit">Sing-up</button>
</form>
</body>
</html>